# Generated by Django 4.1.5 on 2023-02-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('time', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
