# Generated by Django 4.2 on 2023-04-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='bolim',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='profil',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bolim',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
