# Generated by Django 4.2 on 2023-04-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_alter_plan_batafsil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolim',
            name='batafsil',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
