# Generated by Django 4.2 on 2023-04-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0006_remove_profil_user_remove_plan_bolim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='zarurlik',
            field=models.CharField(max_length=12),
        ),
    ]
